/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
//    @Test public void someLibraryMethodReturnsTrue() {
//        basicLibrary.Library classUnderTest = new basicLibrary.Library();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());

    }

