/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Arrays;
import java.util.Random;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    //    Rolling Dice:
    static int[] roll (int n) {
        Random num = new Random();
        int arr[] = new int[n];
        for (int i = 0; i < n; i++) {
            arr[i] = num.nextInt(6) + 1;
        }
        return arr;
    }
    // Contains Duplicates
    static boolean containsDuplicates (int[] arr) {
        int value;
        for (int i = 0; i < arr.length; i++) {
            value = arr[i];
            for (int j = i+1; j < arr.length; j++) {
                if(arr[j] == value){
                    return false;
                }
            }
        }

        return true;
    }

    //    Calculating Averages
    static double Average(int [] integers) {
        double sum = 0 ;
        for (int i = 0; i < integers.length; i++) {
            sum += integers[i];
        }

        return sum/integers.length;
    }

    //    Arrays of Arrays
    static int[] lowAverage(int[][] arr) {
        double avg = 0 , min = Integer.MAX_VALUE;
        int minAvgArr[] = arr[0];
        for (int i = 0; i < arr.length; i++) {
            avg = 0;
            for (int j = 0 ; j < arr[i].length ; j++){
                avg+=arr[i][j];
            }
            avg /= arr[i].length;
            if(avg < min) {
                min = avg;
                minAvgArr = arr[i];
            }

        }
        return minAvgArr;
    }

    public static void main(String[] args) {
        int rollArr[] = roll(4);
        System.out.println(Arrays.toString(rollArr));


        int test[] = {12,13,14,14,15};
        System.out.println(containsDuplicates(test));
        System.out.println(Average(test));

        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        int avgArr[] = lowAverage(weeklyMonthTemperatures);

        System.out.println(Arrays.toString(avgArr));


    }


}
